name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title matches required pattern
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Checking PR title: '$PR_TITLE'"
          if [[ ! "$PR_TITLE" =~ ^\s*[a-zA-Z0-9-]+\s*:\s*.*$ ]]; then
            echo "❌ PR title should begin with a ticket number, e.g MOB-100: <letters/numbers/dash>:<anything> (optional spaces allowed before/after colon)"
            exit 1
          fi
          echo "✅ PR title matches the required pattern."
