name: Test

on:
  - push

jobs:
  test:
    runs-on: [self-hosted, internal-linux]

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Install Flutter
        run: |
          dart pub global activate fvm
          fvm install

      - name: Install project dependencies
        run: fvm flutter pub get

      - name: Get dependencies
        run: fvm flutter pub get

      - name: Run code generation
        run: fvm flutter pub run build_runner build --delete-conflicting-outputs

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Run static analysis
        run: fvm flutter analyze .

      - name: Run tests
        run: fvm flutter test --no-pub --test-randomize-ordering-seed random
